/**
 * Agent browser tabs (spec 00 §7.1–7.4, with DEV-3 from E-B1).
 *
 * Every Agent tab is an offscreen-rendered (`offscreen: true`)
 * `WebContentsView` inside one hidden `BaseWindow`. A hidden window stops
 * `requestAnimationFrame` and IntersectionObserver entirely; offscreen
 * rendering keeps them running at a chosen frame rate, so modern pages load
 * and animate while the user never sees the window. The tab lives
 * independently of any renderer pane: closing or reloading the Browser pane
 * never ends an Agent task.
 *
 * Navigation is checked at three points: the Agent's own loads (pre-check),
 * the page's `will-*` events, and `webRequest` for main-frame and sub-frame
 * requests (redirects included). A committed URL that is not web content
 * closes the tab (fail closed).
 *
 * The hidden window keeps `window-all-closed` from firing, so it is
 * destroyed as soon as the last tab closes and on shutdown.
 */

import { randomUUID } from 'node:crypto'
import { rm } from 'node:fs/promises'
import { join } from 'node:path'
import type {
  DriverEvent,
  NavigationPolicy,
  SitePermissionPolicy,
} from '@emperor/core/host-capabilities'
import type { SitePermissionKind } from '@emperor/core/runtime-contract'
import { UiError } from '@emperor/core/host-capabilities'
import type {
  Certificate,
  Rectangle,
  Session,
  WebContents,
  WebPreferences,
} from 'electron'
import { browserNavigationAllowed } from '../browser-view-policy'
import {
  decideAgentNavigation,
  subframeNavigationAllowed,
} from './agent-navigation-policy'
import type { DownloadInbox } from './download-inbox'
import { ProfileDeletionQueue } from './profile-deletions'
import { hardenSession } from './session-hardening'

export const AGENT_VIEWPORT = { width: 1280, height: 800 } as const

/** Offscreen frame rates: rAF and IntersectionObserver run at this pace. */
export const AGENT_FRAME_RATES = { idle: 2, active: 10, preview: 15 } as const

const ACTIVE_WINDOW_MS = 3_000

export interface ViewLike {
  readonly webContents: WebContents
  setBounds(bounds: Rectangle): void
}

export interface HostLike {
  readonly contentView: {
    addChildView(view: ViewLike): void
    removeChildView(view: ViewLike): void
  }
  destroy(): void
  isDestroyed(): boolean
}

/** Electron constructors, injected so the manager is testable without Electron. */
export interface ElectronFactory {
  createHost(size: { width: number; height: number }): HostLike
  createView(webPreferences: WebPreferences): ViewLike
  sessionFromPartition(partition: string): Session
  /** Persistent profile sessions (`session.fromPath`). */
  sessionFromPath(path: string): Session
}

/** Persistent profile ids are generated by Core: `p_` + 12 hex. */
const PROFILE_ID = /^p_[0-9a-f]{12}$/

export interface AgentTab {
  readonly targetId: string
  readonly ownerSessionId: string
  readonly profileId: string
  /** Temporary partition name, or `profile:<id>` for a persistent profile. */
  readonly partition: string
  readonly session: Session
  readonly view: ViewLike
  readonly contents: WebContents
  generation: number
  revision: number
  paused: boolean
  closed: boolean
  title: string
  loading: boolean
  /** The Agent's own navigation in flight (already authorized). */
  pendingAgentUrl: string | null
  lastError?: string
  activeUntil: number
  previewing: boolean
}

export interface BrowserSessionManagerOptions {
  readonly electron: ElectronFactory
  /** The kernel's navigation verdict (null until a kernel is attached). */
  policy(): NavigationPolicy | null
  emit(event: DriverEvent): void
  readonly viewport?: { width: number; height: number }
  /** `~/.emperor/browser/profiles`; absent: persistent profiles are refused. */
  readonly profilesRoot?: string
  /** Directory removal for deleted profiles (tests inject a fake). */
  removeDirectory?(path: string): Promise<void>
  /** Startup cleanup of deleted profiles (tests may inject a fake). */
  readonly deletions?: Pick<ProfileDeletionQueue, 'mark' | 'reconcile'>
  /** A page's window.open became a new Agent tab (same profile). */
  onPopup?(opener: AgentTab, popup: AgentTab): void
  /** Download inbox; absent: every Agent download is cancelled. */
  readonly downloads?: DownloadInbox
  /** The kernel's site-permission verdict (null: deny everything). */
  sitePermission?(): SitePermissionPolicy | null
  now?(): number
}

/**
 * Electron permission names → the kinds a user can allow. `media` needs
 * every requested device; anything unmapped is always denied.
 */
export function permissionKinds(
  permission: string,
  mediaTypes: readonly string[],
): SitePermissionKind[] | null {
  switch (permission) {
    case 'media': {
      if (mediaTypes.length === 0) return null
      const kinds: SitePermissionKind[] = []
      for (const type of mediaTypes)
        if (type === 'video') kinds.push('camera')
        else if (type === 'audio') kinds.push('microphone')
        else return null
      return kinds
    }
    case 'geolocation':
    case 'notifications':
    case 'clipboard-read':
    case 'fullscreen':
      return [permission]
    case 'clipboard-sanitized-write':
      return ['clipboard-write']
    default:
      return null
  }
}

export function agentTabWebPreferences(
  where: { partition: string } | { session: Session },
): WebPreferences {
  return {
    ...where,
    offscreen: true,
    sandbox: true,
    contextIsolation: true,
    nodeIntegration: false,
    nodeIntegrationInSubFrames: false,
    nodeIntegrationInWorker: false,
    webviewTag: false,
    webSecurity: true,
    allowRunningInsecureContent: false,
    navigateOnDragDrop: false,
    safeDialogs: true,
    spellcheck: false,
    backgroundThrottling: false,
  }
}

export class BrowserSessionManager {
  private host: HostLike | null = null
  private readonly tabs = new Map<string, AgentTab>()
  private readonly byContents = new Map<number, AgentTab>()
  private readonly filteredSessions = new WeakSet<Session>()
  private readonly viewport: { width: number; height: number }
  private readonly now: () => number
  private readonly deletions: Pick<
    ProfileDeletionQueue,
    'mark' | 'reconcile'
  > | null
  private readonly deletionReady: Promise<void>
  private deletionError: unknown = null
  private shuttingDown = false
  private settleTimer: ReturnType<typeof setTimeout> | null = null

  constructor(private readonly options: BrowserSessionManagerOptions) {
    this.viewport = options.viewport ?? AGENT_VIEWPORT
    this.now = options.now ?? Date.now
    this.deletions =
      options.deletions ??
      (options.profilesRoot === undefined
        ? null
        : new ProfileDeletionQueue(options.profilesRoot))
    this.deletionReady = (
      this.deletions?.reconcile() ?? Promise.resolve()
    ).catch((error: unknown) => {
      this.deletionError = error
    })
  }

  private async waitForDeletedProfiles(): Promise<void> {
    await this.deletionReady
    if (this.deletionError !== null)
      throw new UiError(
        'DRIVER_UNAVAILABLE',
        'deleted browser profiles could not be cleaned up',
      )
  }

  get size(): number {
    return this.tabs.size
  }

  get hasHost(): boolean {
    return this.host !== null
  }

  get(targetId: string): AgentTab | undefined {
    const tab = this.tabs.get(targetId)
    return tab === undefined || tab.closed ? undefined : tab
  }

  list(): AgentTab[] {
    return [...this.tabs.values()].filter((tab) => !tab.closed)
  }

  /** Open a new tab and load `url` (already authorized by the kernel). */
  async open(input: {
    ownerSessionId: string
    url: string
    profileId?: string
    /** A popup shares its opener's temporary partition (same cookies). */
    partition?: string
    signal?: AbortSignal
  }): Promise<AgentTab> {
    if (this.shuttingDown)
      throw new UiError('CAPABILITY_DISABLED', 'the browser is shutting down')
    const targetId = `tab_${randomUUID()}`
    const verdict = decideAgentNavigation(
      {
        targetId,
        url: input.url,
        frame: 'main',
        initiator: 'agent',
      },
      this.withOwner(input.ownerSessionId, input.profileId ?? 'temporary'),
    )
    if (verdict === 'block')
      throw new UiError(
        'PERMISSION_REQUIRED',
        `opening ${input.url} is not allowed`,
      )
    const profileId = input.profileId ?? 'temporary'
    const persistent = profileId !== 'temporary'
    if (persistent) await this.waitForDeletedProfiles()
    const partition = persistent
      ? `profile:${profileId}`
      : (input.partition ?? `emperor-task-${randomUUID()}`)
    const session = persistent
      ? this.options.electron.sessionFromPath(this.profilePath(profileId))
      : this.options.electron.sessionFromPartition(partition)
    hardenSession(session, {
      allowPermission: (contents, permission, origin, mediaTypes) => {
        const owner =
          contents === null ? undefined : this.byContents.get(contents.id)
        const kinds = permissionKinds(permission, mediaTypes)
        const policy = this.options.sitePermission?.() ?? null
        if (
          owner === undefined ||
          kinds === null ||
          policy === null ||
          origin === ''
        )
          return false
        return kinds.every((kind) =>
          policy({ targetId: owner.targetId, origin, kind }),
        )
      },
      onDownload: (event, item, contents) => {
        const owner =
          contents === undefined ? undefined : this.byContents.get(contents.id)
        const verdict =
          this.options.downloads?.offer(owner?.targetId, event, item) ??
          (event.preventDefault(), 'blocked' as const)
        if (verdict === 'blocked' && owner !== undefined)
          this.options.emit({
            type: 'download-blocked',
            targetId: owner.targetId,
            url: item.getURL(),
          })
      },
    })
    this.filterRequests(session)
    const view = this.options.electron.createView(
      agentTabWebPreferences(persistent ? { session } : { partition }),
    )
    const contents = view.webContents
    const tab: AgentTab = {
      targetId,
      ownerSessionId: input.ownerSessionId,
      profileId,
      partition,
      session,
      view,
      contents,
      generation: 1,
      revision: 0,
      paused: false,
      closed: false,
      title: '',
      loading: true,
      pendingAgentUrl: input.url,
      activeUntil: this.now() + ACTIVE_WINDOW_MS,
      previewing: false,
    }
    this.tabs.set(targetId, tab)
    this.byContents.set(contents.id, tab)
    this.wire(tab)
    view.setBounds({ x: 0, y: 0, ...this.viewport })
    this.ensureHost().contentView.addChildView(view)
    this.applyFrameRate(tab)
    this.scheduleSettle()
    try {
      await this.load(tab, input.url, input.signal)
    } catch (error) {
      if (error instanceof UiError && error.code === 'PERMISSION_REQUIRED') {
        await this.close(targetId)
        throw error
      }
      // Other load failures leave the tab on Chromium's error page; the
      // Agent sees it in its next observation.
      tab.lastError = error instanceof Error ? error.message : String(error)
    }
    return tab
  }

  /** Agent navigation in an existing tab (already authorized). */
  async navigate(
    targetId: string,
    url: string,
    signal?: AbortSignal,
  ): Promise<void> {
    const tab = this.require(targetId)
    const verdict = decideAgentNavigation(
      {
        targetId,
        url,
        frame: 'main',
        initiator: 'agent',
        ownerSessionId: tab.ownerSessionId,
        profileId: tab.profileId,
      },
      this.options.policy(),
    )
    if (verdict === 'block')
      throw new UiError(
        'PERMISSION_REQUIRED',
        `navigation to ${url} needs permission`,
      )
    tab.pendingAgentUrl = url
    this.touch(targetId)
    await this.load(tab, url, signal)
  }

  /** Where a history move would land, for the kernel's origin check. */
  historyTarget(
    targetId: string,
    direction: 'back' | 'forward' | 'reload',
  ): string | null {
    const tab = this.get(targetId)
    if (tab === undefined) return null
    const history = tab.contents.navigationHistory
    const index =
      history.getActiveIndex() +
      (direction === 'back' ? -1 : direction === 'forward' ? 1 : 0)
    if (index < 0 || index >= history.length()) return null
    return history.getEntryAtIndex(index)?.url ?? null
  }

  async history(
    targetId: string,
    direction: 'back' | 'forward' | 'reload',
  ): Promise<boolean> {
    const tab = this.require(targetId)
    const destination = this.historyTarget(targetId, direction)
    if (destination === null) return false
    const verdict = decideAgentNavigation(
      {
        targetId,
        url: destination,
        frame: 'main',
        initiator: 'agent',
        ownerSessionId: tab.ownerSessionId,
        profileId: tab.profileId,
      },
      this.options.policy(),
    )
    if (verdict === 'block')
      throw new UiError(
        'PERMISSION_REQUIRED',
        `navigation to ${destination} needs permission`,
      )
    tab.pendingAgentUrl = destination
    this.touch(targetId)
    const history = tab.contents.navigationHistory
    if (direction === 'back') history.goBack()
    else if (direction === 'forward') history.goForward()
    else tab.contents.reload()
    return true
  }

  setPaused(targetId: string, paused: boolean): void {
    const tab = this.tabs.get(targetId)
    if (tab !== undefined) tab.paused = paused
  }

  /** Raise the frame rate while the Agent works on a tab. */
  touch(targetId: string): void {
    const tab = this.tabs.get(targetId)
    if (tab === undefined || tab.closed) return
    tab.activeUntil = this.now() + ACTIVE_WINDOW_MS
    this.applyFrameRate(tab)
    this.scheduleSettle()
  }

  private scheduleSettle(): void {
    if (this.settleTimer !== null) clearTimeout(this.settleTimer)
    this.settleTimer = setTimeout(() => {
      this.settleTimer = null
      this.settleFrameRates()
    }, ACTIVE_WINDOW_MS + 100)
    this.settleTimer.unref?.()
  }

  setPreviewing(targetId: string, previewing: boolean): void {
    const tab = this.tabs.get(targetId)
    if (tab === undefined || tab.closed) return
    tab.previewing = previewing
    this.applyFrameRate(tab)
  }

  /** Drop back to the idle frame rate once activity has stopped. */
  settleFrameRates(): void {
    for (const tab of this.list()) this.applyFrameRate(tab)
  }

  async close(targetId: string): Promise<void> {
    const tab = this.tabs.get(targetId)
    if (tab === undefined || tab.closed) return
    tab.closed = true
    this.tabs.delete(targetId)
    this.byContents.delete(tab.contents.id)
    try {
      this.host?.contentView.removeChildView(tab.view)
    } catch {
      // the host may already be gone
    }
    if (!tab.contents.isDestroyed()) tab.contents.close()
    // A temporary profile ends with its last tab; persistent ones persist.
    const shared = [...this.tabs.values()].some(
      (other) => other.partition === tab.partition,
    )
    if (tab.profileId === 'temporary' && !shared)
      await Promise.allSettled([
        tab.session.clearStorageData(),
        tab.session.clearCache(),
      ])
    if (this.tabs.size === 0) this.destroyHost()
  }

  /**
   * Wipe a persistent profile: close its tabs, clear its storage and cache,
   * and with `remove` delete its directory. The Electron session object stays
   * alive until quit, so a deleted profile's id is never reused (Core mints a
   * new id per profile).
   */
  async clearProfile(
    profileId: string,
    options: { remove: boolean },
  ): Promise<void> {
    await this.waitForDeletedProfiles()
    const path = this.profilePath(profileId)
    await Promise.all(
      this.list()
        .filter((tab) => tab.profileId === profileId)
        .map((tab) => this.close(tab.targetId)),
    )
    const session = this.options.electron.sessionFromPath(path)
    await session.clearStorageData()
    await session.clearCache()
    if (options.remove) {
      await this.deletions?.mark(profileId)
      await (
        this.options.removeDirectory ??
        ((dir) => rm(dir, { recursive: true, force: true }))
      )(path)
    }
  }

  private profilePath(profileId: string): string {
    const root = this.options.profilesRoot
    if (root === undefined)
      throw new UiError(
        'CAPABILITY_DISABLED',
        'persistent browser profiles are not available',
      )
    if (!PROFILE_ID.test(profileId))
      throw new UiError('INVALID_REQUEST', `invalid profile id ${profileId}`)
    return join(root, profileId)
  }

  /** Close every Agent tab and the hidden host window; stays usable. */
  async closeAll(): Promise<void> {
    await Promise.allSettled([...this.tabs.keys()].map((id) => this.close(id)))
    this.destroyHost()
  }

  async shutdown(): Promise<void> {
    this.shuttingDown = true
    if (this.settleTimer !== null) clearTimeout(this.settleTimer)
    this.settleTimer = null
    await this.closeAll()
  }

  // ---------------------------------------------------------------------

  private require(targetId: string): AgentTab {
    const tab = this.get(targetId)
    if (tab === undefined)
      throw new UiError('STALE_TARGET', `target ${targetId} is gone`)
    return tab
  }

  private withOwner(
    ownerSessionId: string,
    profileId: string,
  ): NavigationPolicy | null {
    const policy = this.options.policy()
    return policy === null
      ? null
      : (request) => policy({ ...request, ownerSessionId, profileId })
  }

  private ensureHost(): HostLike {
    if (this.host === null || this.host.isDestroyed())
      this.host = this.options.electron.createHost(this.viewport)
    return this.host
  }

  private destroyHost(): void {
    const host = this.host
    this.host = null
    if (host !== null && !host.isDestroyed()) host.destroy()
  }

  private applyFrameRate(tab: AgentTab): void {
    if (tab.contents.isDestroyed()) return
    const fps = tab.previewing
      ? AGENT_FRAME_RATES.preview
      : tab.activeUntil > this.now()
        ? AGENT_FRAME_RATES.active
        : AGENT_FRAME_RATES.idle
    try {
      tab.contents.setFrameRate(fps)
    } catch {
      // not offscreen (tests) or already closing
    }
  }

  private async load(
    tab: AgentTab,
    url: string,
    signal?: AbortSignal,
  ): Promise<void> {
    const loading = tab.contents.loadURL(url)
    if (signal === undefined) {
      await loading
      return
    }
    await Promise.race([
      loading,
      new Promise<never>((_resolve, reject) => {
        if (signal.aborted) reject(new UiError('TIMEOUT_NO_EFFECT', 'aborted'))
        signal.addEventListener(
          'abort',
          () => {
            tab.contents.stop()
            reject(new UiError('TIMEOUT_NO_EFFECT', 'aborted'))
          },
          { once: true },
        )
      }),
    ])
  }

  private async openPopup(opener: AgentTab, url: string): Promise<void> {
    if (opener.closed || this.shuttingDown) return
    try {
      const popup = await this.open({
        ownerSessionId: opener.ownerSessionId,
        url,
        ...(opener.profileId === 'temporary'
          ? { partition: opener.partition }
          : { profileId: opener.profileId }),
      })
      this.options.onPopup?.(opener, popup)
    } catch {
      this.options.emit({
        type: 'popup-blocked',
        targetId: opener.targetId,
        url,
      })
    }
  }

  private judge(
    tab: AgentTab,
    url: string,
    frame: 'main' | 'sub',
    forced?: 'page',
  ): 'allow' | 'block' {
    if (frame === 'sub')
      return subframeNavigationAllowed(url) ? 'allow' : 'block'
    if (tab.paused && tab.pendingAgentUrl !== url && forced === undefined)
      return 'block'
    const initiator = forced ?? (tab.pendingAgentUrl === url ? 'agent' : 'page')
    return decideAgentNavigation(
      {
        targetId: tab.targetId,
        url,
        frame,
        initiator,
        ownerSessionId: tab.ownerSessionId,
        profileId: tab.profileId,
      },
      this.options.policy(),
    )
  }

  private filterRequests(session: Session): void {
    if (this.filteredSessions.has(session)) return
    this.filteredSessions.add(session)
    session.webRequest.onBeforeRequest((details, callback) => {
      const type = details.resourceType
      if (type !== 'mainFrame' && type !== 'subFrame') return callback({})
      const tab =
        details.webContentsId === undefined
          ? undefined
          : this.byContents.get(details.webContentsId)
      if (tab === undefined) return callback({ cancel: true })
      const verdict = this.judge(
        tab,
        details.url,
        type === 'mainFrame' ? 'main' : 'sub',
      )
      if (verdict === 'block' && type === 'mainFrame')
        this.options.emit({
          type: 'navigation-blocked',
          targetId: tab.targetId,
          url: details.url,
        })
      callback(verdict === 'block' ? { cancel: true } : {})
    })
  }

  private wire(tab: AgentTab): void {
    const contents = tab.contents
    const { emit } = this.options
    // window.open never creates a native window: an allowed popup becomes a
    // new Agent tab of the same profile (spec 00 §7.4); the rest is blocked.
    contents.setWindowOpenHandler(({ url }) => {
      if (this.judge(tab, url, 'main', 'page') === 'allow')
        queueMicrotask(() => void this.openPopup(tab, url))
      else emit({ type: 'popup-blocked', targetId: tab.targetId, url })
      return { action: 'deny' }
    })
    const guard =
      (frame: 'main' | 'sub') =>
      (event: { url: string; preventDefault(): void }): void => {
        if (this.judge(tab, event.url, frame) === 'allow') return
        event.preventDefault()
        if (frame === 'main')
          emit({
            type: 'navigation-blocked',
            targetId: tab.targetId,
            url: event.url,
          })
      }
    contents.on('will-navigate', (details) => guard('main')(details))
    contents.on('will-redirect', (details) => {
      if (details.isMainFrame) guard('main')(details)
      else guard('sub')(details)
    })
    contents.on('will-frame-navigate', (details) => {
      if (!details.isMainFrame) guard('sub')(details)
    })
    contents.on('will-attach-webview', (event) => event.preventDefault())
    contents.on('select-client-certificate', (event, _url, _list, callback) => {
      event.preventDefault()
      ;(callback as (certificate?: Certificate) => void)()
    })
    contents.on('did-start-loading', () => {
      tab.loading = true
    })
    contents.on('did-stop-loading', () => {
      tab.loading = false
    })
    contents.on('did-navigate', (_event, url) => {
      // Backstop: a committed main frame must be web content.
      if (!browserNavigationAllowed(url) && url !== 'about:blank') {
        emit({
          type: 'lost',
          targetId: tab.targetId,
          reason: `policy: committed ${url.slice(0, 80)}`,
        })
        void this.close(tab.targetId)
        return
      }
      tab.generation += 1
      tab.revision += 1
      tab.pendingAgentUrl = null
      emit({
        type: 'navigated',
        targetId: tab.targetId,
        url,
        generation: tab.generation,
        revision: tab.revision,
        sameDocument: false,
      })
    })
    contents.on('did-navigate-in-page', (_event, url, isMainFrame) => {
      if (!isMainFrame) return
      tab.revision += 1
      emit({
        type: 'navigated',
        targetId: tab.targetId,
        url,
        generation: tab.generation,
        revision: tab.revision,
        sameDocument: true,
      })
    })
    contents.on('page-title-updated', (_event, title) => {
      tab.title = title
      emit({ type: 'title', targetId: tab.targetId, title })
    })
    contents.on('render-process-gone', (_event, details) => {
      emit({
        type: 'lost',
        targetId: tab.targetId,
        reason: `render-process-gone: ${details.reason}`,
      })
      void this.close(tab.targetId)
    })
  }
}
