import { createApp } from 'vue'
import App from './App.vue'
import { router } from './router'
import { applyTheme, DEFAULT_THEME } from './theme/tokens'
import './styles.css'
import './theme/dark.css'
import './theme/light.css'
import './theme/base.css'
import './styles/materials.css'
import './styles/a11y.css'
import './styles/layout.css'
import './styles/chat.css'
import './styles/activity.css'
import './styles/panels.css'
import './styles/responsive.css'
import './styles/surfaces/shell-base.css'
import './styles/surfaces/messages.css'
import './styles/surfaces/goal.css'
import './styles/surfaces/composer.css'
import './styles/surfaces/cards.css'
import './styles/surfaces/decision.css'
import './styles/surfaces/menus.css'
import './styles/surfaces/panels.css'
import './styles/surfaces/sidebar.css'
import './styles/surfaces/settings.css'
import './styles/workspace.css'
import './styles/files-highlight.css'

applyTheme(document, localStorage.getItem('emperor.theme') ?? DEFAULT_THEME)

createApp(App).use(router).mount('#app')
