import type { Config } from 'tailwindcss'

/* dsh 设计系统(M3):全部由 theme/{dark,light}.css 的 CSS 变量驱动。
   实色 token 是 RGB 三元组 → 支持 /<alpha> 修饰;半透明叠层(l1-l4、
   interactive-*)是完整颜色值 → 不支持 alpha 修饰。 */
const rgb = (name: string) => `rgb(var(--${name}) / <alpha-value>)`
const NB_STEPS = [
  '00',
  '50',
  '60',
  '75',
  '100',
  '150',
  '200',
  '300',
  '400',
  '500',
  '600',
  '700',
  '750',
  '800',
  '850',
  '875',
  '900',
  '950',
  '1000',
] as const
const nbScale = Object.fromEntries(
  NB_STEPS.map((step) => [`nb-${step}`, rgb(`nb-${step}`)]),
)
const solid = (names: string[]) =>
  Object.fromEntries(names.map((name) => [name, rgb(name)]))
const dsColors = {
  ...nbScale,
  surface: rgb('bg-base'),
  'layer-1': rgb('bg-layer-1'),
  'layer-2': rgb('bg-layer-2'),
  'layer-3': rgb('bg-layer-3'),
  overlay: rgb('bg-overlay'),
  sidebar: rgb('sidebar-fill'),
  'sidebar-hover': rgb('sidebar-item-hover'),
  'sidebar-active': rgb('sidebar-item-active'),
  menu: rgb('menu-fill'),
  selector: rgb('selector-fill'),
  tip: rgb('tip-fill'),
  'input-major': rgb('input-major'),
  'code-block': rgb('code-block-bg'),
  'code-banner': rgb('code-banner-bg'),
  'inline-code': rgb('inline-code-bg'),
  tooltip: rgb('tooltip-bg'),
  toast: rgb('toast-bg'),
  'toast-fg': rgb('toast-fg'),
  'primary-fill': rgb('button-primary-fill'),
  'primary-hover': rgb('button-primary-hover'),
  'primary-fg': rgb('button-primary-fg'),
  ...solid([
    'label-primary',
    'label-secondary',
    'label-tertiary',
    'label-caption',
    'label-dimmed',
    'label-inverted',
    'accent-fill',
    'accent-hover',
    'accent-strong',
    'accent-soft',
    'accent-soft-strong',
    'bubble-user',
    'focus-ring',
    'approval',
    'approval-strong',
    'approval-line',
    'approval-soft',
    'ok-soft',
    'warn-soft',
    'danger-soft',
    'code-constant',
    'code-string',
    'code-comment',
    'code-keyword',
    'code-parameter',
    'code-function',
    'code-punctuation',
    'code-link',
  ]),
  l1: 'var(--border-l1)',
  l2: 'var(--border-l2)',
  l3: 'var(--border-l3)',
  l4: 'var(--border-l4)',
  'interactive-hover': 'var(--interactive-bg-hover)',
  'interactive-active': 'var(--interactive-bg-active)',
  'interactive-danger': 'var(--interactive-bg-hover-danger)',
}
const dsFontSize = (size: string) =>
  [`var(--fs-${size})`, { lineHeight: `var(--lh-${size})` }] as [
    string,
    { lineHeight: string },
  ]

export default {
  content: ['./src/renderer/index.html', './src/renderer/src/**/*.{vue,ts}'],
  theme: {
    extend: {
      colors: {
        /* semantic Codex tokens */
        bg: 'rgb(var(--bg) / <alpha-value>)',
        'bg-elevated': 'rgb(var(--bg-elevated) / <alpha-value>)',
        'bg-inset': 'rgb(var(--bg-inset) / <alpha-value>)',
        fg: 'rgb(var(--fg) / <alpha-value>)',
        /* grok 式文本层级:fg 叠 text-* alpha(玻璃上透出环境色) */
        secondary: 'rgb(var(--fg) / var(--text-secondary))',
        tertiary: 'rgb(var(--fg) / var(--text-tertiary))',
        border: 'rgb(var(--border) / <alpha-value>)',
        'border-strong': 'rgb(var(--border-strong) / <alpha-value>)',
        accent: 'rgb(var(--accent) / <alpha-value>)',
        'accent-fg': 'rgb(var(--accent-fg) / <alpha-value>)',
        brand: 'rgb(var(--brand) / <alpha-value>)',
        danger: 'rgb(var(--danger) / <alpha-value>)',
        warn: 'rgb(var(--warn) / <alpha-value>)',
        ok: 'rgb(var(--ok) / <alpha-value>)',
        /* categorical tones (capability tags / data-tone) */
        'tone-cyan': 'rgb(var(--tone-cyan) / <alpha-value>)',
        'tone-violet': 'rgb(var(--tone-violet) / <alpha-value>)',
        'tone-blue': 'rgb(var(--tone-blue) / <alpha-value>)',
        ...dsColors,
      },
      borderRadius: {
        row: 'var(--radius-row)',
        cell: 'var(--radius-cell)',
        card: 'var(--radius-card)',
        takeover: 'var(--radius-takeover)',
        composer: 'var(--radius-composer)',
        modal: 'var(--radius-modal)',
      },
      fontSize: {
        xxxs: dsFontSize('xxxs'),
        xxs: dsFontSize('xxs'),
        'ds-xs': dsFontSize('xs'),
        'ds-s': dsFontSize('s'),
        'ds-base': dsFontSize('base'),
        'ds-md': dsFontSize('md'),
        code: dsFontSize('code'),
      },
      fontFamily: {
        display: ['var(--font-sans)'],
        body: ['var(--font-sans)'],
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-md)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        imperial: '0 8px 28px rgb(var(--shadow-color) / 0.28)',
        insetPaper: 'inset 0 0 0 1px rgb(var(--border) / 0.7)',
        lv1: 'var(--shadow-lv1)',
        lv2: 'var(--shadow-lv2)',
        lv3: 'var(--shadow-lv3)',
      },
      zIndex: {
        base: 'var(--z-base)',
        raised: 'var(--z-raised)',
        sticky: 'var(--z-sticky)',
        overlay: 'var(--z-overlay)',
        drawer: 'var(--z-drawer)',
        popover: 'var(--z-popover)',
        toast: 'var(--z-toast)',
        modal: 'var(--z-modal)',
        menu: 'var(--z-menu)',
        lightbox: 'var(--z-lightbox)',
      },
      transitionDuration: {
        instant: 'var(--duration-instant)',
        fast: 'var(--duration-fast)',
        DEFAULT: 'var(--duration)',
        slow: 'var(--duration-slow)',
        'ds-fast': 'var(--duration-ds-fast)',
        ds: 'var(--duration-ds)',
        'ds-slow': 'var(--duration-ds-slow)',
      },
      transitionTimingFunction: {
        apple: 'var(--ease-out)',
        spring: 'var(--ease-spring)',
        'apple-in': 'var(--ease-in)',
        ds: 'var(--ease-in-out)',
      },
      backgroundImage: {
        grain:
          'linear-gradient(180deg, rgb(var(--bg)) 0%, rgb(var(--bg-inset)) 100%)',
      },
      animation: {
        'rise-in': 'rise-in 520ms ease both',
        'pulse-seal': 'pulse-seal 1.8s ease-in-out infinite',
      },
      keyframes: {
        'rise-in': {
          '0%': { opacity: '0', transform: 'translateY(14px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'pulse-seal': {
          '0%, 100%': { opacity: '0.42', transform: 'scale(1)' },
          '50%': { opacity: '1', transform: 'scale(1.18)' },
        },
      },
    },
  },
  plugins: [],
} satisfies Config
